import { useState, useEffect } from 'react'
import { isConfigured, generateAltText } from '../api/accessibilityClient'

/**
 * Content image whose alt text can be generated by the Accessibility Services
 * microservice (/v1/alt-text). If the service is configured and reachable, the
 * generated caption replaces `fallbackAlt`; otherwise the human-authored
 * `fallbackAlt` is used. The image is never left without an accessible name.
 *
 * IMPORTANT: use this only for MEANINGFUL images. Decorative images must keep
 * alt="" (or aria-hidden) — do not run alt-text generation on them.
 */
export default function AltImage({ src, fallbackAlt = '', lang = 'en', ...rest }) {
  const [alt, setAlt] = useState(fallbackAlt)

  useEffect(() => {
    if (!isConfigured()) return
    let active = true
    generateAltText(src, lang)
      .then((text) => {
        if (active && text) setAlt(text)
      })
      .catch(() => {
        /* keep fallbackAlt on any failure/503 */
      })
    return () => {
      active = false
    }
  }, [src, lang])

  return <img src={src} alt={alt} {...rest} />
}
